### ISSUE TITLE
Breaks on Django 2.0

### ISSUE THREAD

**Issue by flexpeace** [dmpayton/django-admin-honeypot#48] opened 2017-12-13 13:27 UTC
ModuleNotFoundError: No module named 'django.core.urlresolvers'

**Comment by phyxkal** [comment] 2017-12-21 16:16
u can use django.urls

**Comment by kwill** [comment] 2018-01-16 14:06
I think this is a duplicate of #45

**Comment by gtlambert** [comment] 2018-03-07 16:26
@phyxkal how can we use django.urls? I'm finding the `django-admin-honeypot` breaks on Django version 2.0.2

**Comment by dmpayton** [comment] 2018-05-15 00:47
1.1.0 has been released, now with more Django 2 compatibility! 🎉

**Closed by dmpayton** 2018-05-15 00:47 UTC
